language: python

python:
  - "2.7"

cache:
  - apt

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gir1.2-gtk-3.0 python-cairo python-gi python-gi-cairo python-gobject python-gobject-2 python-gobject-dev python-paramiko
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python -m unittest tests
